# Generated by Django 2.2.2 on 2019-07-01 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearpublished', models.SmallIntegerField()),
                ('minplayers', models.PositiveSmallIntegerField()),
                ('maxplayers', models.PositiveSmallIntegerField()),
                ('minplaytime', models.PositiveSmallIntegerField()),
                ('maxplaytime', models.PositiveSmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=4, max_digits=4)),
                ('bggurl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardgames', models.ManyToManyField(to='collection.BoardGame')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
