# Generated by Django 2.2.2 on 2019-07-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
