# Generated by Django 2.2.3 on 2019-07-08 02:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("collection", "0002_boardgame_name"),
    ]

    operations = [migrations.RenameModel(old_name="User", new_name="SiteUser")]
