# Generated by Django 2.2.3 on 2019-07-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20190708_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='bggid',
            field=models.PositiveSmallIntegerField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
