# Generated by Django 2.2.3 on 2019-07-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_boardgame_bggid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='weight',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
